name: Spiralgeometry
channels:
  - conda-forge
dependencies:
  - acoular
  - traits >=4.4 # Version aus dem Acoular requirement.txt übernommen
  - scipy >=1.7  # Version aus dem Acoular requirement.txt übernommen
  - ipython
  - numpy
  - matplotlib
  - pandas
